const menuItems=[
{name:"Espresso",ar:"إسبريسو",category:"coffee",price:"1.50"},{name:"Americano",ar:"أمريكانو",category:"coffee",price:"2.00"},{name:"Black",ar:"بلاك",category:"coffee",price:"2.00"},{name:"V60",ar:"V60",category:"coffee",price:"3.50"},{name:"V60 — Hula",ar:"V60 — هولا",category:"coffee",price:"4.00"},{name:"V60 — Raspberry",ar:"V60 — راسبيري",category:"coffee",price:"5.00"},{name:"Cortado",ar:"كورتادو",category:"coffee",price:"2.00"},{name:"Flat White",ar:"فلات وايت",category:"coffee",price:"2.00"},{name:"Cold Brew",ar:"كولد برو",category:"coffee",price:"3.00"},{name:"Latte",ar:"لاتيه",category:"coffee",price:"3.00"},{name:"Cappuccino",ar:"كابتشينو",category:"coffee",price:"3.00"},
{name:"House Latte",ar:"هاوس لاتيه",category:"signature",price:"3.50"},{name:"Berries Latte",ar:"بيريز لاتيه",category:"signature",price:"3.50"},{name:"Sal-Scot Latte",ar:"سال-سكوت لاتيه",category:"signature",price:"3.50"},{name:"Baked Latte",ar:"بيكد لاتيه",category:"signature",price:"3.50"},{name:"Arabian Latte",ar:"أرابيان لاتيه",category:"signature",price:"4.00"},
{name:"Arabian Night",ar:"أرابيان نايت",category:"frappe",price:"3.50"},{name:"Toxic",ar:"توكسيك",category:"frappe",price:"3.50"},{name:"Choco Blossom",ar:"شوكو بلوسوم",category:"frappe",price:"3.50"},{name:"Silk Road",ar:"سيلك رود",category:"frappe",price:"3.50"},{name:"Nutz",ar:"نتز",category:"frappe",price:"3.50"},
{name:"Mad",ar:"ماد",category:"matcha",price:"4.00"},{name:"Glad",ar:"غلاد",category:"matcha",price:"4.00"},{name:"Meeeh",ar:"مييه",category:"matcha",price:"4.00"},{name:"Cozy",ar:"كوزي",category:"matcha",price:"4.00"},{name:"Frozy",ar:"فروزي",category:"matcha",price:"4.00"},
{name:"Wall-Nuts",ar:"وول-نتس",category:"shake",price:"5.00"},{name:"Zesty",ar:"زيستي",category:"shake",price:"5.00"},{name:"Mera-Mieh",ar:"ميرا-ميه",category:"shake",price:"5.00"},{name:"Player",ar:"بلاير",category:"shake",price:"5.00"},{name:"Surprise Me",ar:"فاجئني",category:"shake",price:"5.00"},
{name:"Extra Shot",ar:"شوت إضافي",category:"extras",price:"0.50"},{name:"Syrup",ar:"سيرب",category:"extras",price:"0.50"},{name:"Whipped Cream",ar:"كريمة مخفوقة",category:"extras",price:"0.50"},{name:"Still Water",ar:"مياه عادية",category:"extras",price:"0.50"},{name:"Sparkling Water",ar:"مياه غازية",category:"extras",price:"0.50"},{name:"Coconut Milk",ar:"حليب جوز الهند",category:"extras",price:"0.75"},{name:"Almond Milk",ar:"حليب اللوز",category:"extras",price:"0.75"},{name:"Lactose Free",ar:"خالي من اللاكتوز",category:"extras",price:"0.50"}
];
const order=["coffee","signature","frappe","matcha","shake","extras"];
const meta={en:{coffee:["Coffee Classics","Espresso, pour-over and milk-based essentials."],signature:["House Signatures","Our distinctive latte collection."],frappe:["Frappe","Cold, blended House creations."],matcha:["Matcha Moods","Five different shades of green."],shake:["Milkshakes","Rich, playful and made to linger."],extras:["Extras","Shots, syrups, water and milk alternatives."]},ar:{coffee:["كلاسيكيات القهوة","إسبريسو، قهوة مقطرة ومشروبات الحليب."],signature:["مشروبات ذا هاوس","مجموعة اللاتيه المميزة لدينا."],frappe:["فرابيه","خلطات ذا هاوس الباردة."],matcha:["مزاج الماتشا","خمس نكهات ماتشا مختلفة."],shake:["ميلك شيك","غني، ممتع ومصمم للاستمتاع."],extras:["الإضافات","شوتات، سيرب، مياه وبدائل الحليب."]}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const body=document.body,topbar=$("#topbar"),progress=$(".progress span"),loader=$(".loader"),menuButton=$(".menu-button"),mobilePanel=$(".mobile-panel"),langButton=$(".lang"),menuList=$("#menu-list"),search=$("#menu-search"),resultCount=$("#result-count"),clearSearch=$("#clear-search"),film=$(".house-film"),filmFrame=$(".film-frame"),filmPlay=$(".film-play"),soundToggle=$(".sound-toggle"),pointerLight=$(".pointer-light");
let language=localStorage.getItem("house-flagship-language")==="ar"?"ar":"en",activeCategory="all",query="";
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function setLanguage(lang){language=lang;localStorage.setItem("house-flagship-language",lang);document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";body.classList.toggle("is-ar",lang==="ar");langButton.textContent=lang==="ar"?"EN":"AR";$$('[data-en]').forEach(el=>el.textContent=el.dataset[lang]);search.placeholder=search.dataset[lang==="ar"?"placeholderAr":"placeholderEn"];renderMenu();updateMoodText(document.querySelector(".mood.active").dataset.mood)}
function renderMenu(){const cats=activeCategory==="all"?order:[activeCategory];let visible=0;const html=cats.map((cat,ci)=>{const items=menuItems.filter(i=>i.category===cat&&(`${i.name} ${i.ar}`).toLowerCase().includes(query.toLowerCase()));if(!items.length)return"";visible+=items.length;const m=meta[language][cat];return`<section class="category-block" style="--c:${ci}"><header class="category-header"><span>${String(order.indexOf(cat)+1).padStart(2,"0")}</span><div><h3>${escapeHtml(m[0])}</h3><p>${escapeHtml(m[1])}</p></div></header>${items.map((item,i)=>`<article class="menu-item" style="--i:${i}"><span>${String(i+1).padStart(2,"0")}</span><h4>${escapeHtml(language==="ar"?item.ar:item.name)}</h4><span class="leader"></span><strong class="price">${item.price}<small>JD</small></strong></article>`).join("")}</section>`}).join("");menuList.innerHTML=html||`<div class="menu-empty"><strong>0</strong><h3>${language==="ar"?"لا توجد نتائج":"No menu matches"}</h3><p>${language==="ar"?"جرّب اسماً آخر أو امسح البحث.":"Try another name or clear the search."}</p></div>`;resultCount.textContent=language==="ar"?`${visible} عنصر`: `${visible} ${visible===1?"item":"items"}`;clearSearch.hidden=!query}
$$('.tab').forEach(tab=>tab.addEventListener("click",()=>{$$('.tab').forEach(t=>{t.classList.remove("active");t.setAttribute("aria-selected","false")});tab.classList.add("active");tab.setAttribute("aria-selected","true");activeCategory=tab.dataset.category;renderMenu()}));search.addEventListener("input",()=>{query=search.value.trim();renderMenu()});clearSearch.addEventListener("click",()=>{search.value="";query="";renderMenu();search.focus()});
function toggleNav(force){const open=typeof force==="boolean"?force:!body.classList.contains("nav-open");body.classList.toggle("nav-open",open);menuButton.classList.toggle("active",open);menuButton.setAttribute("aria-expanded",String(open));mobilePanel.classList.toggle("open",open);mobilePanel.setAttribute("aria-hidden",String(!open))}menuButton.addEventListener("click",()=>toggleNav());$$('.mobile-panel a').forEach(a=>a.addEventListener("click",()=>toggleNav(false)));document.addEventListener("keydown",e=>{if(e.key==="Escape")toggleNav(false)});langButton.addEventListener("click",()=>setLanguage(language==="en"?"ar":"en"));
const moods={en:{morning:"Quiet light. First pour. Clear mind.",focus:"A table, steady energy and room to think.",night:"Warm lights. Slow time. One more conversation."},ar:{morning:"ضوء هادئ، أول كوب، وذهن صافٍ.",focus:"طاولة، طاقة ثابتة، ومساحة للتفكير.",night:"إضاءة دافئة، وقت أبطأ، وحوار إضافي."}};function updateMoodText(m){$("#mood-caption").textContent=moods[language][m]}$$('.mood').forEach(btn=>btn.addEventListener("click",()=>{$$('.mood').forEach(b=>{b.classList.remove("active");b.setAttribute("aria-selected","false")});btn.classList.add("active");btn.setAttribute("aria-selected","true");body.dataset.mood=btn.dataset.mood;updateMoodText(btn.dataset.mood)}));body.dataset.mood="morning";
film.addEventListener("loadeddata",()=>filmFrame.classList.add("ready"));film.addEventListener("canplay",()=>filmFrame.classList.add("ready"));filmPlay.addEventListener("click",async()=>{try{if(film.paused){await film.play();filmFrame.classList.add("playing")}else{film.pause();filmFrame.classList.remove("playing")}}catch{filmFrame.classList.remove("playing")}});film.addEventListener("click",()=>{if(!film.paused){film.pause();filmFrame.classList.remove("playing")}});soundToggle.addEventListener("click",()=>{film.muted=!film.muted;soundToggle.classList.toggle("on",!film.muted);soundToggle.querySelector("b").textContent=language==="ar"?(film.muted?"الصوت مغلق":"الصوت يعمل"):(film.muted?"Sound off":"Sound on")});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");revealObserver.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>revealObserver.observe(el));
window.addEventListener("scroll",()=>{topbar.classList.toggle("scrolled",scrollY>30);const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?scrollY/max*100:0}%`},{passive:true});
if(matchMedia("(hover:hover) and (pointer:fine)").matches){window.addEventListener("pointermove",e=>{pointerLight.style.left=e.clientX+"px";pointerLight.style.top=e.clientY+"px";pointerLight.style.opacity="1"});const tilt=$("[data-tilt]");tilt.addEventListener("pointermove",e=>{const r=tilt.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;tilt.style.transform=`rotateY(${x*7}deg) rotateX(${-y*6}deg)`});tilt.addEventListener("pointerleave",()=>tilt.style.transform="");$$('.magnetic').forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener("pointerleave",()=>el.style.transform="")})}
window.addEventListener("load",()=>setTimeout(()=>loader.classList.add("hide"),700));setTimeout(()=>loader.classList.add("hide"),2500);$("#year").textContent=new Date().getFullYear();setLanguage(language);renderMenu();
